version: "3.8"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=car_dealership
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"